# Story: list all descendants of each role.

prefix : <http://data.europa.eu/a4g/ontology/cv/transitivity-test#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>

select *
where {
	?concept a skos:Concept .
	?concept skos:narrowerTransitive ?t .
	optional {?t skos:narrowerTransitive ?nt .}
}
