# Story: list all descendants of the role 'Buyer'

PREFIX : <http://data.europa.eu/a4g/ontology/cv/roles-taxonomy#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?role WHERE {
	 ?concept skos:narrower ?roleObject .
	 ?concept skos:broader :buy .
 	 ?roleObject skos:prefLabel ?role .
}