# Story: List the winners of all procedures
PREFIX test: <http://example.org/test-abox#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX epo: <http://data.europa.eu/a4g/ontology/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>

############### Option 1 ################
SELECT ?involvement ?agent ?role ?procedure
WHERE {
    ?pivObject epo:involvesAgent ?agentObject ;
        		epo:involvesRole ?roleObject ;
          		epo:involvesProcedure ?procedureObject ;
               	dct:description ?involvement .
    ?roleObject rdfs:label ?role .
    ?agentObject rdfs:label ?agent .
    ?procedureObject epo:title ?procedure .
    FILTER EXISTS {?roleObject rdf:type epo:Winner}
}

############### Option 2 ################
SELECT ?involvement ?agent ?role
WHERE {
    ?pivObject epo:involvesAgent ?agentObject ;
        		epo:involvesRole ?roleObject ; 
               	dct:description ?involvement .
    ?roleObject rdf:type epo:Winner ;
                rdfs:label ?role .
    ?agentObject rdfs:label ?agent .
}

############### Option 3 ################
 SELECT ?involvement ?agent ?role
 WHERE {
    ?pivObject  epo:involvesAgent ?agentObject ;
        		epo:involvesWinner ?roleObject ;
               	dct:description ?involvement .
    ?roleObject rdfs:label ?role .
    ?agentObject rdfs:label ?agent .
}
