== Abstract

_In 2016 the link:++https://publications.europa.eu/en/home++[Publications Office of the European Union] (Publications Office or OP) started a project funded by the
 link:https://ec.europa.eu/isa2/home_en[ISA Programme] to organise and support the development of a Public Procurement Ontology (ePO)._

_The ultimate objective of the ontology is to put forth a commonly agreed OWL ontology that will conceptualise, formally encode and make available in an open,
structured and machine-readable format data about public procurement, covering it from end to end, i.e. from notification, through tendering to awarding, ordering, invoicing and payment.
With this goal in mind the OP engaged a Working Group (WG) of experts with the mission of building consensus on the analysis results and deliverables developed by the OP's teams._

_By mid-2017 a version 1.00 of the Ontology was delivered and submitted to the Working group for discussion. All the materials related to this version were made public and are accessible
through the ISA2 link:https://joinup.ec.europa.eu/solution/eprocurement-ontology[Joinup] platform; including the discussions held in the Working Group (WG)._

_A new stage of the development, identified as ePO v2.0.0, was initiated in January 2018. The goal of this new version is to improve and extend the previous version._

_This document describes the objectives, the methodological approach and the deliverables produced in this new version._
